authentication/urls.py
from django.urls import path
from . import views
from core import views as app_views


app_name = "authentication"

urlpatterns = [
    path("", app_views.home, name="home"),
    # sign up
    path("sign-up/", views.sign_up, name="sign_up"),
    # sign in
    path("sign-in/", views.sign_in, name="sign_in"),
    # sign out
    path("sign-out/", views.sign_out, name="sign_out"),
    # user's profile
    path("user/", views.user, name="user"),
    # user change password
    path("user/password", views.updatePassword, name="changePassword"),
    # user's cv
    path("user/cvPublic/<int:id>", views.cvPublic, name="cvPublic"),
    # user's profile picture
    path("user/<int:id>/photo", views.photo, name="photo"),
    # company's profile picture
    path("company/<int:id>/photo", views.company_photo, name="entity"),
    # school's profile picture
    path("school/<int:id>/photo", views.school_photo, name="entity"),
    # user's forgot password
    path("user/forgotPassword", views.forgotPassword, name="forgotPassword"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    # home
    path("", views.home, name="home"),
    # user's profile
    path("profile", views.profile, name="profile"),
    # about page
    path("about", views.about, name="about"),
    # cgu page
    path("cgu", views.cgu, name="cgu"),
    # legal mentions page
    path("legal", views.legal, name="legal"),
    # policy page
    path("policies", views.policies, name="policies"),
    # student details
    path("student/<int:student_id>", views.student_detail, name="student_detail"),
    # company details
    path("company/<int:company_id>", views.company_detail, name="company_detail"),
    # school details
    path("school/<int:school_id>", views.school_detail, name="school_detail"),
]

job/urls.py
from django.urls import path
from . import views

# Url mappings related to job resource
urlpatterns = [
    # list of jobs
    path("", views.list_jobs, name="list_jobs"),
    # job detail
    path("<int:job_id>/", views.job_detail, name="job_detail"),
    # update a job
    path("update/<int:job_id>/", views.update_job, name="update_job"),
    # inspect all jobs datings (company only)
    path("<int:job_id>/inspect", views.job_inspect, name="job_inspect"),
    # preview of a job (api)
    path("preview/<int:job_id>/", views.preview_job, name="preview_job"),
    # create a job (company only)
    path("create-job/", views.create_job, name="create_job"),
    # job datings page
    path("datings/", views.jobs_datings, name="jobs_datings"),
    # job datings details (company only)
    path(
        "datings/<int:job_dating_id>",
        views.jobs_datings_detail,
        name="jobs_datings_detail",
    ),
    # job datings inspect cv (company only)
    path(
        "datings/<int:job_dating_id>/inspect-cv",
        views.job_dating_inspect_cv,
        name="job_dating_inspect_cv",
    ),
    # job datings inspect motivation letter (company only)
    path(
        "datings/<int:job_dating_id>/inspect-letter",
        views.job_dating_inspect_letter,
        name="job_dating_inspect_letter",
    ),
]

un_alternant_une_solution_webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("authentication.urls")),
    path("jobs/", include("job.urls")),
    path("courses/", include("course.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("webpush/", include("webpush.urls")),
    path("", include("core.urls")),
]

core/views.py
from http.client import NOT_FOUND
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from authentication.models import Company, School, Student, User
from job.models import Job

# Create your views here.


# home view
def home(request):
    # get three latest published jobs, and the webpush options, and return them to the home page
    webpush = {"group": "alternant"}
    latest_jobs = Job.objects.all().order_by("-create_at")[:3]
    return render(request, "home.html", {"webpush": webpush, "jobs": latest_jobs})


# about view, just return the about page
def about(request):
    return render(request, "about.html")


# cgu view, just return the contact page
def cgu(request):
    return render(request, "CGU.html")


# legal mentions view, just return the legal mentions page
def legal(request):
    return render(request, "legal.html")


# policy view, just return the policy page
def policies(request):
    return render(request, "policies.html")


# student details view
def student_detail(request, student_id):

    try:

        # get the student by id from the url parameter
        student = list(
            Student.objects.filter(id=student_id).values(
                "id",
                "user_id",
                "birthday",
                "linkedin_url",
                "cv_path",
                "description",
                "linkedin_url",
            )
        )[0]

        # get the user associated with the student
        user_info = list(
            User.objects.filter(id=student["user_id"]).values(
                "id", "first_name", "last_name", "email", "extension_picture"
            )
        )[0]

        # return the student and the user to the student_detail page
        return render(
            request, "student_detail.html", {"student": student, "user_info": user_info}
        )

    # if the student does not exist, return a 404 error
    except Student.DoesNotExist:
        return HttpResponse("Student does not exist", status=NOT_FOUND)


# company details view
def company_detail(request, company_id):
    try:

        # get the company by id from the url parameter
        company = list(
            Company.objects.filter(id=company_id).values(
                "id", "name", "description", "city", "street", "zip_code"
            )
        )[0]

        # return the company infor to the company_detail page
        return render(request, "company_detail.html", {"company": company})

    # if the company does not exist, return a 404 error
    except Company.DoesNotExist:
        return HttpResponse("Company does not exist", status=NOT_FOUND)


# school details view
def school_detail(request, school_id):
    try:

        # get the school by id from the url parameter
        school = list(
            School.objects.filter(id=school_id).values(
                "id", "name", "description", "city", "street", "zip_code"
            )
        )[0]

        # return the school infor to the school_detail page
        return render(request, "school_detail.html", {"school": school})

    # if the school does not exist, return a 404 error
    except School.DoesNotExist:
        return HttpResponse("School does not exist", status=NOT_FOUND)


# profile view (must be logged in)
@login_required
def profile(request):

    # get the user from the request
    user_data = list(User.objects.filter(id=request.user.id).values())[0]
    user_type = request.user.getUserType()
    data = None

    # if the user is a student, get the student data
    if user_type == "student":
        data = list(
            Student.objects.filter(user=request.user).values(
                "id",
                "user_id",
                "birthday",
                "linkedin_url",
                "cv_path",
                "description",
                "course__name",
            )
        )[0]

    # if the user is a company, get the company data
    elif user_type == "company":
        data = list(Company.objects.filter(users=request.user).values())[0]

    # if the user is a school, get the school data
    else:
        data = list(School.objects.filter(users=request.user).values())[0]

    # return the user data to the profile page
    return render(
        request,
        "profile.html",
        {"data": data, "user": user_data, "userType": user_type},
    )

core/templates/components/footer.html
{% load i18n %}
<footer>
  <div class="bg-primary w-full h-full p-5 lg:p-10 flex items-center">
    <div class="flex flex-col lg:flex-row justify-start items-center w-full px-10">
      <div>
        <img src="../../static/assets/logo.png" alt="" class="w-56">
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-3 text-center lg:text-left gap-8 lg:gap-20 lg:ml-20 mt-10 lg:mt-0">
        <div class="w-full">
          <h2 class="text-white font-bold">{% trans 'APropos' %}</h2>
          <ul class="text-white font-medium mt-10">
            <li><a href="/cgu" class="hover:text-secondary">{% trans 'APropos' %}</a></li>
            <li><a href="/legal" class="hover:text-secondary">{% trans 'Mentions légales' %}</a></li>
            <li><a href="/policies" class="hover:text-secondary">{% trans 'Politique de confidentialité' %}</a></li>
          </ul>
        </div>
        <div class="w-full">
          <h2 class="text-white font-bold">{% trans 'Plan du site' %}</h2>
          <ul class="text-white font-medium mt-10">
            <li><a href="/cgu" class="hover:text-secondary">{% trans 'APropos' %}</a></li>
            <li><a href="/legal" class="hover:text-secondary">{% trans 'Mentions légales' %}</a></li>
            <li><a href="/policies" class="hover:text-secondary">{% trans 'Politique de confidentialité' %}</a></li>
          </ul>
        </div>
        <div class="w-full">
          <h2 class="text-white font-bold">{% trans 'Newsletter' %}</h2>
          <ul class="text-white font-medium mt-10">
            <li><a href="/cgu" class="hover:text-secondary">{% trans 'APropos' %}</a></li>
            <li><a href="/legal" class="hover:text-secondary">{% trans 'Mentions légales' %}</a></li>
            <li><a href="/policies" class="hover:text-secondary">{% trans 'Politique de confidentialité' %}</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

core/templates/components/meta.html
<!DOCTYPE html>

<html lang="en" data-theme="light">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {% load static %}

  {# FAVICON #}
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
  <link rel="mask-icon" href="{% static 'favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
  <link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}" type="image/x-icon">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">


  {# STYLE #}
  <link rel="stylesheet" href="{% static 'styles/css/app.css' %}" />

  {# HOT RELOAD SCRIPT #}
  {# <script src="https://livejs.com/live.js" defer></script>#}

  {# FONT AWESOME SCRIPT #}
  <script
    src="https://gistcdn.githack.com/Lilian-MMI/f23496a8c50ca94d62ec20d0d3591851/raw/52867fe3589247dd300846262e0a71866326cfd6/fontawesome.min.js">
  </script>

  {# DAISYUI #}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/daisyui/2.9.0/full.min.css"
    integrity="sha512-cRY3HtkOja2mHLEvA0tgwuaVysmMN2PijT7mRN3Lj4WfqCDdnDKAoSPk250WAGBGbLmMaBqZT2qCZNA2Pngk5A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  {# TAILWINDCSS #}
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = {
      theme: {
        extend: {
          colors: {
            primary: "#00AFB9",
            secondary: "#243A48",
          },
          container: {
            center: true,
          },
        },
      },
    };
  </script>

  {# TOASTIFY #}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastify-js/1.11.2/toastify.min.js"
    integrity="sha512-zrRn+TvTc4KgDOtlKOgThphx1DGCZ8zR/xGWtG/WiKp6G+/xUBWow3p2lWu8DHfdHYWfwvIY0I89b3q22POHSw=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastify-js/1.11.2/toastify.min.css"
    integrity="sha512-ecfz7BsZIyMBMdXTx7GU2128lQ7MTiqGJwAqCumba6v8y7YDhYEHueqy+iUtUdZsnsKhCyoCcFGGMhpwQOy6xg=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  {# VUEJS #}
  <script src="https://unpkg.com/vue@3"></script>

  {% load webpush_notifications %}
  {% webpush_header %}

  <script>
    const getCookie = (c_name) => {
      if (document.cookie.length > 0) {
        c_start = document.cookie.indexOf(c_name + "=");
        if (c_start != -1) {
          c_start = c_start + c_name.length + 1;
          c_end = document.cookie.indexOf(";", c_start);
          if (c_end == -1) c_end = document.cookie.length;
          return unescape(document.cookie.substring(c_start, c_end));
        }
      }
      return "";
    }
  </script>

  <style>
    /* VUEJS TRANSITION */
    .fade-enter-active,
    .fade-leave-active {
      transition: opacity 0.5s ease;
    }

    .fade-enter-from,
    .fade-leave-to {
      opacity: 0;
    }

    * {
      box-sizing: border-box;
      /* SCROLLBAR */
      scrollbar-width: thin;
      scrollbar-color: rgba(0, 0, 0, 0.3) transparent;
    }

    /* SCROLLBAR */
    *::-webkit-scrollbar,
    *::-webkit-scrollbar-thumb {
      width: 10px;
      height: 10px;
      border-radius: 13px;
      background-clip: padding-box;
      border: 2px solid transparent;
      color: rgba(0, 0, 0, 0.3);
      background: transparent;
    }

    *::-webkit-scrollbar-thumb {
      box-shadow: inset 0 0 0 10px;
    }
  </style>

  <title>1alternant1solution</title>
</head>

</html>

core/templates/components/navbar.html
{% load i18n %}
<nav class="flex flex-col justify-center bg-primary w-full z-50 top-0 sticky shadow-lg">
  <div class="container flex flex-row justify-between items-center px-8 w-full">
    <div class="flex flex-row items-center">
      <a href="/" class="mr-8">
        <img class="w-48 md:w-36" alt="Marketplace logo" src="../../static/assets/logo.png" />
      </a>
      <div class="hidden lg:block">
        <a href="/" class="text-white text-sm hover:text-secondary font-bold">{% trans 'Home' %}</a>
        <a href="/jobs" class="text-white text-sm hover:text-secondary font-bold ml-4">{% trans 'Apprenticeship' %}</a>
        <a href="/courses" class="text-white text-sm hover:text-secondary font-bold ml-4">{% trans 'Courses' %}</a>
        <a href="/about" class="text-white text-sm hover:text-secondary font-bold ml-4">{% trans 'APropos' %}</a>
      </div>
    </div>
    <div class="block lg:hidden cursor-pointer" v-on:click="toggleMenu()">
      <i class="fas fa-bars text-white text-2xl hover:text-secondary"></i>
    </div>
    <div class="hidden lg:block">
      <div class="flex flex-row items-center">
        <div class="dropdown dropdown-hover dropdown-end">

          <a href="{% url 'core:profile' %}" class="text-white text-sm hover:text-secondary font-bold ml-4">
            <i class="fas fa-user-circle hover:text-secondary text-white text-2xl ml-4"></i>
          </a>
          
          <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-secondary  text-white rounded-box w-52">
            <li><a href="{% url 'authentication:sign_out' %}">{% trans 'Déconnexion' %}</a></li>
          </ul>

        </div>


        <div class="flex pl-5">


          <button
          data-tip=""
          style="box-shadow: 2px 0px 10px -5px rgba(0,0,0,0.39);"
            class="button-push-accept tooltip tooltip-bottom text-white text-sm font-bold bg-primary py-2 px-8 w-14 h-14 rounded-full hover:text-secondary flex justify-center items-center cursor-pointer">FFF</button>

          {% load webpush_notifications %}

          {% webpush_button with_class="hidden text-white text-sm font-bold bg-secondary py-2 px-8 w-48 h-14 rounded-full hover:text-primary flex justify-center items-center cursor-pointer" %}
        </div>
        <div class="flex pl-10">
          {% csrf_token %}
          <input name="next" id='nextInputFlag' type="hidden" value="{{ redirect_to }}">
          <div class="flag pr-2 cursor-pointer" v-on:click="changeLang('fr')">🇫🇷</div>
          <div class="flag pr-2 cursor-pointer" v-on:click="changeLang('en')">🇬🇧</div>
          <div class="flag cursor-pointer" v-on:click="changeLang('cn')">🇨🇳</div>
        </div>

      </div>
    </div>

  </div>

  <div class="lg:hidden bg-secondary h-[400px] shadow-xl flex flex-col items-center justify-center space-y-4"
    v-show="displayMenu === true">
    <div>
      <a href="/" class="text-white text-sm hover:text-primary font-bold">{% trans 'Home' %}</a>
    </div>
    <div>
      <a href="/jobs" class="text-white text-sm hover:text-primary font-bold">{% trans 'Apprenticeship' %}</a>
    </div>
    <div>
      <a href="/courses" class="text-white text-sm hover:text-primary font-bold">{% trans 'Courses' %}</a>
    </div>
    <div>
      <a href="/about" class="text-white text-sm hover:text-primary font-bold">{% trans 'APropos' %}</a>
    </div>


    <div class="flex flex-col items-center">
      
      <button
          data-tip=""
          style="box-shadow: 2px 0px 10px -5px rgba(0,0,0,0.39);"
            class="button-push-accept tooltip tooltip-bottom text-white text-sm font-bold bg-secondary py-2 px-8 w-14 h-14 rounded-full hover:text-primary flex justify-center items-center cursor-pointer">FFF</button>
      {% load webpush_notifications %}

      {% webpush_button with_class="hidden text-white text-sm font-bold bg-secondary py-2 px-8 w-48 h-14 rounded-full hover:text-primary flex justify-center items-center cursor-pointer" %}
     
      <div class="flex lg:pl-10">

        {% csrf_token %}
        <input name="next" id='nextInputFlag' type="hidden" value="{{ redirect_to }}">
        <div class="flag pr-2 cursor-pointer" v-on:click="changeLang('fr')">🇫🇷</div>
        <div class="flag pr-2 cursor-pointer" v-on:click="changeLang('en')">🇬🇧</div>
        <div class="flag cursor-pointer" v-on:click="changeLang('cn')">🇨🇳</div>
      </div>

    </div>

    <div class="dropdown dropdown-hover dropdown-end">
      <a href="{% url 'core:profile' %}" class="text-white text-sm hover:text-primary font-bold">
        <i class="fas fa-user-circle hover:text-primary text-white text-2xl"></i>
      </a>

      <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-secondary  text-white rounded-box w-52">
        <li><a href="{% url 'authentication:sign_out' %}">{% trans 'Déconnexion' %}</a></li>
      </ul>
    </div>
  </div>
  </div>
</nav>

{% block vueJs %}
<script>
  const app = Vue.createApp({
    delimiters: ["[[", "]]"],
    data() {
      return {
        displayMenu: false
      }
    },
    methods: {

      //This function is used to toggle the menu
      toggleMenu: function () {
        this.displayMenu = !this.displayMenu
      },

      // This function is called when the user clicks on the flag icon in the navbar 
      // to change the language of the website to French or English or Chinese respectively and it's use Django's i18n endpoint.
      changeLang: async function (lang) {

        const details = {
          language: lang,
          next: document.getElementById("nextInputFlag").value
        };

        let formBody = [];
        for (const property in details) {
          const encodedKey = encodeURIComponent(property);
          const encodedValue = encodeURIComponent(details[property]);
          formBody.push(encodedKey + "=" + encodedValue);
        }
        formBody = formBody.join("&");

        await fetch('/i18n/setlang/', {
          body: formBody,
          method: 'POST',
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
            "X-CSRFToken": document.getElementsByName("csrfmiddlewaretoken")[0].value
          },
        })
        .then((response) => location.reload())

        window.location.reload()
      },
      
      setButtonText() {
        let button_push_accept = document.getElementsByClassName("button-push-accept");

        if (localStorage.getItem("popupNotif") === null || localStorage.getItem("popupNotif") === 'false') {
          button_push_accept.item(0).innerHTML = `<i class="fas fa-bell"></i>`;
          button_push_accept.item(0).dataset.tip = `{% trans 'Subscribe to Push Messaging' %}`;
          button_push_accept.item(1).innerHTML = `<i class="fas fa-bell"></i>`;
          button_push_accept.item(1).dataset.tip = `{% trans 'Subscribe to Push Messaging' %}`;
          
          
        } else {
          button_push_accept.item(0).innerHTML = `<i class="fas fa-bell-slash"></i>`;
          button_push_accept.item(0).dataset.tip = `{% trans 'Unsubscribe from Push Messaging' %}`;
          button_push_accept.item(1).innerHTML = `<i class="fas fa-bell-slash"></i>`;
          button_push_accept.item(1).dataset.tip = `{% trans 'Unsubscribe from Push Messaging' %}`;
        }
      },
    },
    mounted() {
      let webpush_subscribe_button = document.getElementById("webpush-subscribe-button");

      let button_push_accept = document.getElementsByClassName("button-push-accept");
      this.setButtonText()
      button_push_accept.item(0).onclick = () => {
        webpush_subscribe_button.click();
        //localStorage.setItem("popupNotif",true)
        if (localStorage.getItem("popupNotif") === null || localStorage.getItem("popupNotif") === 'false') {
          localStorage.setItem("popupNotif", 'true')
        } else {
          localStorage.setItem("popupNotif", 'false')
        }

        this.setButtonText()
      };

      button_push_accept.item(1).onclick = () => {
        webpush_subscribe_button.click();

        //localStorage.setItem("popupNotif",true)
        if (localStorage.getItem("popupNotif") === null || localStorage.getItem("popupNotif") === 'false') {
          localStorage.setItem("popupNotif", 'true')
        } else {
          localStorage.setItem("popupNotif", 'false')
        }
        this.setButtonText()

      }
    },
  }).mount("#app");
</script>
{% endblock %}