authentication/urls.py
from django.urls import path
from . import views
from core import views as app_views


app_name = "authentication"

urlpatterns = [
    path("", app_views.home, name="home"),
    # sign up
    path("sign-up/", views.sign_up, name="sign_up"),
    # sign in
    path("sign-in/", views.sign_in, name="sign_in"),
    # sign out
    path("sign-out/", views.sign_out, name="sign_out"),
    # user's profile
    path("user/", views.user, name="user"),
    # user change password
    path("user/password", views.updatePassword, name="changePassword"),
    # user's cv
    path("user/cvPublic/<int:id>", views.cvPublic, name="cvPublic"),
    # user's profile picture
    path("user/<int:id>/photo", views.photo, name="photo"),
    # company's profile picture
    path("company/<int:id>/photo", views.company_photo, name="entity"),
    # school's profile picture
    path("school/<int:id>/photo", views.school_photo, name="entity"),
    # user's forgot password
    path("user/forgotPassword", views.forgotPassword, name="forgotPassword"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    # home
    path("", views.home, name="home"),
    # user's profile
    path("profile", views.profile, name="profile"),
    # about page
    path("about", views.about, name="about"),
    # cgu page
    path("cgu", views.cgu, name="cgu"),
    # legal mentions page
    path("legal", views.legal, name="legal"),
    # policy page
    path("policies", views.policies, name="policies"),
    # student details
    path("student/<int:student_id>", views.student_detail, name="student_detail"),
    # company details
    path("company/<int:company_id>", views.company_detail, name="company_detail"),
    # school details
    path("school/<int:school_id>", views.school_detail, name="school_detail"),
]

job/urls.py
from django.urls import path
from . import views

# Url mappings related to job resource
urlpatterns = [
    # list of jobs
    path("", views.list_jobs, name="list_jobs"),
    # job detail
    path("<int:job_id>/", views.job_detail, name="job_detail"),
    # update a job
    path("update/<int:job_id>/", views.update_job, name="update_job"),
    # inspect all jobs datings (company only)
    path("<int:job_id>/inspect", views.job_inspect, name="job_inspect"),
    # preview of a job (api)
    path("preview/<int:job_id>/", views.preview_job, name="preview_job"),
    # create a job (company only)
    path("create-job/", views.create_job, name="create_job"),
    # job datings page
    path("datings/", views.jobs_datings, name="jobs_datings"),
    # job datings details (company only)
    path(
        "datings/<int:job_dating_id>",
        views.jobs_datings_detail,
        name="jobs_datings_detail",
    ),
    # job datings inspect cv (company only)
    path(
        "datings/<int:job_dating_id>/inspect-cv",
        views.job_dating_inspect_cv,
        name="job_dating_inspect_cv",
    ),
    # job datings inspect motivation letter (company only)
    path(
        "datings/<int:job_dating_id>/inspect-letter",
        views.job_dating_inspect_letter,
        name="job_dating_inspect_letter",
    ),
]

un_alternant_une_solution_webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("authentication.urls")),
    path("jobs/", include("job.urls")),
    path("courses/", include("course.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("webpush/", include("webpush.urls")),
    path("", include("core.urls")),
]

core/views.py
from http.client import NOT_FOUND
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from authentication.models import Company, School, Student, User
from job.models import Job

# Create your views here.


# home view
def home(request):
    # get three latest published jobs, and the webpush options, and return them to the home page
    webpush = {"group": "alternant"}
    latest_jobs = Job.objects.all().order_by("-create_at")[:3]
    return render(request, "home.html", {"webpush": webpush, "jobs": latest_jobs})


# about view, just return the about page
def about(request):
    return render(request, "about.html")


# cgu view, just return the contact page
def cgu(request):
    return render(request, "CGU.html")


# legal mentions view, just return the legal mentions page
def legal(request):
    return render(request, "legal.html")


# policy view, just return the policy page
def policies(request):
    return render(request, "policies.html")


# student details view
def student_detail(request, student_id):

    try:

        # get the student by id from the url parameter
        student = list(
            Student.objects.filter(id=student_id).values(
                "id",
                "user_id",
                "birthday",
                "linkedin_url",
                "cv_path",
                "description",
                "linkedin_url",
            )
        )[0]

        # get the user associated with the student
        user_info = list(
            User.objects.filter(id=student["user_id"]).values(
                "id", "first_name", "last_name", "email", "extension_picture"
            )
        )[0]

        # return the student and the user to the student_detail page
        return render(
            request, "student_detail.html", {"student": student, "user_info": user_info}
        )

    # if the student does not exist, return a 404 error
    except Student.DoesNotExist:
        return HttpResponse("Student does not exist", status=NOT_FOUND)


# company details view
def company_detail(request, company_id):
    try:

        # get the company by id from the url parameter
        company = list(
            Company.objects.filter(id=company_id).values(
                "id", "name", "description", "city", "street", "zip_code"
            )
        )[0]

        # return the company infor to the company_detail page
        return render(request, "company_detail.html", {"company": company})

    # if the company does not exist, return a 404 error
    except Company.DoesNotExist:
        return HttpResponse("Company does not exist", status=NOT_FOUND)


# school details view
def school_detail(request, school_id):
    try:

        # get the school by id from the url parameter
        school = list(
            School.objects.filter(id=school_id).values(
                "id", "name", "description", "city", "street", "zip_code"
            )
        )[0]

        # return the school infor to the school_detail page
        return render(request, "school_detail.html", {"school": school})

    # if the school does not exist, return a 404 error
    except School.DoesNotExist:
        return HttpResponse("School does not exist", status=NOT_FOUND)


# profile view (must be logged in)
@login_required
def profile(request):

    # get the user from the request
    user_data = list(User.objects.filter(id=request.user.id).values())[0]
    user_type = request.user.getUserType()
    data = None

    # if the user is a student, get the student data
    if user_type == "student":
        data = list(
            Student.objects.filter(user=request.user).values(
                "id",
                "user_id",
                "birthday",
                "linkedin_url",
                "cv_path",
                "description",
                "course__name",
            )
        )[0]

    # if the user is a company, get the company data
    elif user_type == "company":
        data = list(Company.objects.filter(users=request.user).values())[0]

    # if the user is a school, get the school data
    else:
        data = list(School.objects.filter(users=request.user).values())[0]

    # return the user data to the profile page
    return render(
        request,
        "profile.html",
        {"data": data, "user": user_data, "userType": user_type},
    )

core/templates/about.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}

<div id="about flex ">
    <div class="max-w-screen-lg mx-auto my-16 px-8">
        <h1 class="text-3xl text-secondary font-bold text-center mb-16">
            {% trans 'Qui sommes-nous ?' %}
        </h1>
        <p>
            {% trans 'Qui sommes-nous ?2' %}
        </p>

        <p class="mt-4">
            {% trans 'Qui sommes-nous ?3' %}
        </p>

        <p class="mt-4">
            {% trans 'Qui sommes-nous ?4' %}
        </p>

        <p class="mt-4">
            {% trans 'Qui sommes-nous ?5' %}
        </p>

        <p class="mt-4">
            {% trans 'Qui sommes-nous ?6' %}
        </p>

        <p class="mt-4">
            {% trans 'Qui sommes-nous ?7' %}
        </p>
    </div>
    <div class="mb-24">
        <div class="w-4/6 mx-auto my-16 px-4">
            <h1 class="text-3xl text-secondary font-bold text-center mb-16">
                {% trans 'Notre équipe' %}
            </h1>
        </div>
        <div class="flex justify-center flex-wrap w-full">
            <div class="avatar mx-16 flex flex-col mt-6 w-full sm:w-1/4 lg:w-fit">
                <div class="w-24 mx-auto rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
                    <img
                        src="https://media-exp1.licdn.com/dms/image/C4D03AQGe5DlEcJMiVw/profile-displayphoto-shrink_200_200/0/1632319742113?e=2147483647&v=beta&t=6pLIVpOHR369bBxCGwMNOGtg1Km4ItVmhD6mhqraEF0" />
                </div>
                <span class="mx-auto font-bold mt-3">KOTTO Yann</span>
            </div>
            <div class="avatar mx-16 flex flex-col mt-6 w-full sm:w-1/4 lg:w-fit">
                <div class="w-24 mx-auto rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
                    <img src="https://www.babelio.com/users/AVT_Tom-Leveque_487.jpg" />
                </div>
                <span class="mx-auto font-bold mt-3">LEVEQUE Tom</span>
            </div>
            <div class="avatar mx-16 flex flex-col mt-6 w-full sm:w-1/4 lg:w-fit">
                <div class="w-24 mx-auto rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
                    <img
                        src="https://media-exp1.licdn.com/dms/image/C4D03AQGULMZx8XdctQ/profile-displayphoto-shrink_200_200/0/1605795324670?e=1652918400&v=beta&t=zA_FYQcBO_OSZSE2nEIOe5_hMJhPRFPzIUNjEfwOaDk" />
                </div>
                <span class="mx-auto font-bold mt-3">OUVRARD Lilian</span>
            </div>
            <div class="avatar mx-16 flex flex-col mt-6 w-full sm:w-1/4 lg:w-fit">
                <div class="w-24 mx-auto rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
                    <img
                        src="https://media-exp1.licdn.com/dms/image/C5603AQElMrZBBPxg7g/profile-displayphoto-shrink_200_200/0/1561275134418?e=2147483647&v=beta&t=EPJ_Y7FtWfyVOV1_iBIx0MSVhMRfZzRQz6Q1Qx7vSCU" />
                </div>
                <span class="mx-auto font-bold mt-3">KAYM Kassai</span>
            </div>
        </div>
    </div>
</div>


{% include './components/footer.html' %}

{% endblock %}

core/templates/base.html
{% include "./components/meta.html" %}

<div data-theme="rtrt" id="app">
    {% include './components/navbar.html'%}
    {% block content %}
    {% endblock %}
</div>

{% block vueJs %}{% endblock %}

core/templates/company_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}

<div class="container flex flex-col items-center justify-between mt-20 h-full">
  <div class="avatar">
    <div class="w-36 rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
      <img src="/auth/company/{{company.id}}/photo" />
    </div>
  </div>
  <div class="text-center mt-10">
    <p class="font-bold text-xl">{{company.name}}</p>
    <p class="badge bg-primary border-none mt-2">- {% trans 'Entreprise' %} -</p>
  </div>
  <div class="mt-5 flex flex-col items-center space-x-2">
    <p class="font-medium italic">{{company.city}}</p>

    <p class="font-medium italic">{{company.street}}, {{company.zip_code}}</p>

  </div>
  <div class="self-start mt-10 space-y-5 border-[1px] border-gray-200 w-full rounded-md h-full p-5">
    <h2 class="font-medium">{% trans 'Description' %}:</h2>
    <p>{{company.description}}
    </p>
  </div>

  <div class="mt-10">
    <a href="" class="btn bg-secondary hover:bg-primary rounded-md border-none">{% trans 'Contacter' %}</a>
  </div>
</div>

<div class="mt-20">
  {% include './components/footer.html' %}
</div>

{% endblock %}

core/templates/home.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}


{% include './components/home/hero.html' %}

<div class="mt-20">{% include './components/home/section1.html' %}</div>
<div class="mt-20">{% include './components/home/section2.html' %}</div>
<div class="mt-20">{% include './components/home/section3.html' %}</div>

<div class="mt-20">{% include './components/footer.html' %}</div>

{% endblock %}

core/templates/legal.html
{% extends "base.html" %}


{% block content %}

<div class="my-16 flex w-full">
    <div class="mx-auto max-w-screen-lg">
        <h2 class="font-bold text-secondary text-xl lg:text-2xl mb-6"> MENTIONS LÉGALES</h2>

        Conformément aux dispositions de la loi n° 2004-575 du 21 juin 2004 pour la confiance en l'économie numérique,
        il est
        précisé aux utilisateurs du site 1alternant 1solution l'identité des différents intervenants dans le cadre de sa
        réalisation et de son suivi.
        <br>
        <br>
        <strong>
            Edition du site
        </strong>

        Le présent site, accessible à l’URL https://un-alternant-une-solution.herokuapp.com/ (le « Site »), est édité
        par :

        ynov ynov, résidant 2 rue de l'échappée 75010 PARIS, de nationalité Française (France), né(e) le 22/01/2000,
        <br>
        <br>
        <strong>

            Hébergement
        </strong>

        Le Site est hébergé par la société heroku, situé 2 rue de l'échappée 75010 PARIS., (contact téléphonique ou
        email :
        +33845126584).
        <br>
        <br>
        <strong>
            Directeur de publication
        </strong>

        Le Directeur de la publication du Site est ynov ynov.
        <br>
        <br>
        <strong>
            Nous contacter
        </strong>

        Par téléphone : +33782876578
        Par email : rgege@gmail.com
        Par courrier : 2 rue de l'échappée 75010 PARIS

    </div>
</div>


{% include './components/footer.html' %}

{% endblock %}

core/templates/policies.html
{% extends "base.html" %}


{% block content %}
<div class="my-16 flex w-full">
    <div class="mx-auto max-w-screen-lg">
        <h2 class="font-bold text-secondary text-xl lg:text-2xl mb-6 font-uppercase">Politiques de confidentialités</h2>

        <p>At 1alternant 1solution, accessible from https://un-alternant-une-solution.herokuapp.com/, one of our main
            priorities
            is the privacy of our visitors. This Privacy Policy document contains types of information that is collected
            and
            recorded by 1alternant 1solution and how we use it.</p>

        <p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to
            contact us.
        </p>

        <p>This Privacy Policy applies only to our online activities and is valid for visitors to our website with
            regards to
            the information that they shared and/or collect in 1alternant 1solution. This policy is not applicable to
            any
            information collected offline or via channels other than this website. Our Privacy Policy was created with
            the help
            of the <a href="https://www.privacypolicygenerator.info">Free Privacy Policy Generator</a>.</p>
        <br>
        <br>
        <strong>Consent</strong>

        <p>By using our website, you hereby consent to our Privacy Policy and agree to its terms.</p>
        <br>
        <br>
        <strong>Information we collect</strong>

        <p>The personal information that you are asked to provide, and the reasons why you are asked to provide it, will
            be made
            clear to you at the point we ask you to provide your personal information.</p>
        <p>If you contact us directly, we may receive additional information about you such as your name, email address,
            phone
            number, the contents of the message and/or attachments you may send us, and any other information you may
            choose to
            provide.</p>
        <p>When you register for an Account, we may ask for your contact information, including items such as name,
            company
            name, address, email address, and telephone number.</p>
        <br>
        <br>
        <strong>How we use your information</strong>

        <p>We use the information we collect in various ways, including to:</p>

        <ul>
            <li>Provide, operate, and maintain our website</li>
            <li>Improve, personalize, and expand our website</li>
            <li>Understand and analyze how you use our website</li>
            <li>Develop new products, services, features, and functionality</li>
            <li>Communicate with you, either directly or through one of our partners, including for customer service, to
                provide
                you with updates and other information relating to the website, and for marketing and promotional
                purposes</li>
            <li>Send you emails</li>
            <li>Find and prevent fraud</li>
        </ul>
        <br>
        <br>
        <strong>Log Files</strong>

        <p>1alternant 1solution follows a standard procedure of using log files. These files log visitors when they
            visit
            websites. All hosting companies do this and a part of hosting services' analytics. The information collected
            by log
            files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time
            stamp,
            referring/exit pages, and possibly the number of clicks. These are not linked to any information that is
            personally
            identifiable. The purpose of the information is for analyzing trends, administering the site, tracking
            users'
            movement on the website, and gathering demographic information.</p>



        <br>
        <br>
        <strong>Advertising Partners Privacy Policies</strong>

        <P>You may consult this list to find the Privacy Policy for each of the advertising partners of 1alternant
            1solution.
        </p>

        <p>Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are
            used
            in
            their respective advertisements and links that appear on 1alternant 1solution, which are sent directly to
            users'
            browser. They automatically receive your IP address when this occurs. These technologies are used to measure
            the
            effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on
            websites
            that you visit.</p>

        <p>Note that 1alternant 1solution has no access to or control over these cookies that are used by third-party
            advertisers.</p>
        <br>
        <br>
        <strong>Third Party Privacy Policies</strong>

        <p>1alternant 1solution's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising
            you to
            consult the respective Privacy Policies of these third-party ad servers for more detailed information. It
            may
            include their practices and instructions about how to opt-out of certain options. </p>

        <p>You can choose to disable cookies through your individual browser options. To know more detailed information
            about
            cookie management with specific web browsers, it can be found at the browsers' respective websites.</p>
        <br>
        <br>
        <strong>CCPA Privacy Rights (Do Not Sell My Personal Information)</strong>

        <p>Under the CCPA, among other rights, California consumers have the right to:</p>
        <p>Request that a business that collects a consumer's personal data disclose the categories and specific pieces
            of
            personal data that a business has collected about consumers.</p>
        <p>Request that a business delete any personal data about the consumer that a business has collected.</p>
        <p>Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</p>
        <p>If you make a request, we have one month to respond to you. If you would like to exercise any of these
            rights,
            please
            contact us.</p>
        <br>
        <br>
        <strong>GDPR Data Protection Rights</strong>

        <p>We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled
            to the
            following:</p>
        <p>The right to access – You have the right to request copies of your personal data. We may charge you a small
            fee for
            this service.</p>
        <p>The right to rectification – You have the right to request that we correct any information you believe is
            inaccurate.
            You also have the right to request that we complete the information you believe is incomplete.</p>
        <p>The right to erasure – You have the right to request that we erase your personal data, under certain
            conditions.</p>
        <p>The right to restrict processing – You have the right to request that we restrict the processing of your
            personal
            data, under certain conditions.</p>
        <p>The right to object to processing – You have the right to object to our processing of your personal data,
            under
            certain conditions.</p>
        <p>The right to data portability – You have the right to request that we transfer the data that we have
            collected
            to
            another organization, or directly to you, under certain conditions.</p>
        <p>If you make a request, we have one month to respond to you. If you would like to exercise any of these
            rights,
            please
            contact us.</p>
        <br>
        <br>
        <strong>Children's Information</strong>

        <p>Another part of our priority is adding protection for children while using the internet. We encourage parents
            and
            guardians to observe, participate in, and/or monitor and guide their online activity.</p>

        <p>1alternant 1solution does not knowingly collect any Personal Identifiable Information from children under the
            age of
            13. If you think that your child provided this kind of information on our website, we strongly encourage you
            to
            contact us immediately and we will do our best efforts to promptly remove such information from our records.
        </p>
    </div>
</div>


{% include './components/footer.html' %}

{% endblock %}

core/templates/school_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}

<div class="container flex flex-col items-center justify-between mt-20 h-full">
  <div class="avatar">
    <div class="w-36 rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
      <img src="/auth/school/{{school.id}}/photo" />
    </div>
  </div>
  <div class="text-center mt-10">
    <p class="font-bold text-xl">{{school.name}}</p>
    <p class="badge bg-primary border-none mt-2">- {% trans 'École' %} -</p>
  </div>
  <div class="mt-5 flex flex-col items-center space-x-2">
    <p class="font-medium italic">{{school.city}}</p>

    <p class="font-medium italic">{{school.street}}, {{school.zip_code}}</p>

  </div>
  <div class="self-start mt-10 space-y-5 border-[1px] border-gray-200 w-full rounded-md h-full p-5">
    <h2 class="font-medium">{% trans 'Description' %}:</h2>
    <p>{{school.description}}
    </p>
  </div>

  <div class="mt-10">
    <a href="" class="btn bg-secondary hover:bg-primary rounded-md border-none">{% trans 'Contacter' %}</a>
  </div>
</div>

<div class="mt-20">
  {% include './components/footer.html' %}
</div>

{% endblock %}

core/templates/student_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}

<div class="container flex flex-col items-center justify-between mt-20 h-full">
  <div class="avatar">
    <div class="w-36 rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
      <img src="/auth/user/{{user_info.id}}/photo" />
    </div>
  </div>
  <div class="text-center mt-10">
    <p class="font-bold text-xl">{{user_info.first_name}} {{user_info.last_name}}
      <a href="{{student.linkedin_url}}" target="blank" class="ml-4"><i class="fa fa-linkedin text-blue-500"></i></a>
    </p>
    <p>23 ans</p>
    <p class="badge bg-primary border-none mt-2">- {% trans 'Étudiant' %} -</p>

  </div>
  <div class="mt-5 flex flex-row space-x-2">

    <a href="{% url 'authentication:cvPublic' 1 %}" target="_blank"
      class="btn bg-secondary hover:bg-primary rounded-md border-none"><i class="fas fa-download mr-4"></i>
      {% trans 'Télécharger le CV' %}</a>
  </div>
  <div class="self-start mt-10 space-y-5 border-[1px] border-gray-200 w-full rounded-md h-full p-5">
    <h2 class="font-bold text-lg">{% trans 'Description' %}:</h2>
    <p>{{student.description}}</p>
  </div>

  <div class="mt-10">
    <a href="mailto:{{user_info.email}}" class="btn bg-secondary hover:bg-primary rounded-md border-none">{% trans 'Contacter' %}</a>
  </div>
</div>

<div class="mt-20">
  {% include './components/footer.html' %}
</div>

{% endblock %}